Mobiteli/Controllers/PhoneController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Mobiteli.Models;
using PagedList;

namespace Mobiteli.Controllers
{ 
    public class PhoneController : Controller
    {
        private EvidencijaEntities db = new EvidencijaEntities();

        //
        // GET: /Phone/

        public ViewResult Index(string sortOrder, string currentFilter, string searchString, int? page, string rbSve)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "Ime desc" : "";
            ViewBag.BrojSortParm = sortOrder == "Broj" ? "Broj desc" : "Broj";
            ViewBag.Title = "Zaduženje brojeva";

            if (Request.HttpMethod == "GET")
            {
                searchString = currentFilter;
            }
            else
            {
                page = 1;
            }
            ViewBag.CurrentFilter = searchString;

            ViewBag.RadioVal = 1;

            var students = from s in db.Telefonija.Include("Operateri").Include("Zaposlenici").Include("Tip_Telefona")
                           select s;

            if (!String.IsNullOrEmpty(searchString))
            {
                students = students.Where(s => s.Zaposlenici.ImePrezime.ToUpper().Contains(searchString.ToUpper())
                                       || s.broj_tel.ToUpper().Contains(searchString.ToUpper()));
            }

            if(rbSve == null)
                rbSve = "akt";

            if (!String.IsNullOrEmpty(rbSve))
            {
                if(rbSve == "akt")
                    students = students.Where(s => s.dat_deakt == null);
                 
                if(rbSve == "isk")
                    students = students.Where(s => s.dat_deakt != null);
            }

            switch (sortOrder)
            {
                case "Ime desc":
                    students = students.OrderByDescending(s => s.Zaposlenici.ImePrezime);
                    break;
                case "Broj":
                    students = students.OrderBy(s => s.broj_tel);
                    break;
                case "Broj desc":
                    students = students.OrderByDescending(s => s.broj_tel);
                    break;
                default:
                    students = students.OrderBy(s => s.Zaposlenici.ImePrezime);
                    break;
            }
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(students.ToPagedList(pageNumber, pageSize)); 
        }

        public ActionResult CheckVisibility(int radioValue)
        {
            return Json(new
            {
                // based on the value of the radio decide whether 
                // the textbox should be shown 
                visible = radioValue == 1
            }, JsonRequestBehavior.AllowGet);
        } 


        //
        // GET: /Phone/Details/5

        public ViewResult Details(int id)
        {
            Telefonija telefonija = db.Telefonija.Single(t => t.id_tel == id);
            return View(telefonija);
        }

        public ViewResult PotrosnjaPage()
        {
            var telefonija = db.spPotrosnja();
            return View(telefonija);
        }

        public ActionResult ReportPage(string id)
        {
            var potr = (from p in db.vPotrosnjaMjesec where p.lnk== id  orderby p.ImePrezime select p);

            return View(potr);
        }
        //
        // GET: /Phone/Create

        public ActionResult Create()
        {
            ViewBag.id_zaposlenici = new SelectList(db.Zaposlenici.OrderBy(t => t.ImePrezime), "id_zaposlenici", "ImePrezime");
            ViewBag.id_tip = new SelectList(db.Tip_Telefona, "id_tip", "Naziv");
            ViewBag.id_oper = new SelectList(db.Operateri,"id_oper","Naziv");
            return View();
        }

        public ActionResult SumarnoPage(int id)
        {
            ViewBag.id_tel = id;

            var telefonija = (from t in db.PotrosnjaSumarno where t.id_tel == id select t).ToList();
            var zb = (from t in db.PotrosnjaSumarno where t.id_tel == id select t.iznos).Sum();
            if (zb != null) ViewBag.zbroj = Math.Round((double)zb, 2).ToString("0.00");

            decimal? zb1 = (from t in telefonija select t.limit).Sum();
            ViewBag.zbrojb = Math.Round((double)zb1, 2).ToString("0.00");

            decimal? zb2 = (from t in telefonija select t.iznos_kor).Sum();
            ViewBag.zbrojk = Math.Round((double)zb2, 2).ToString("0.00");


            var kor  =
                (from tt in db.Telefonija
                 where tt.id_tel == id
                 select new { ime = tt.Zaposlenici.ImePrezime + " - " + tt.broj_tel}).FirstOrDefault();
            if (kor != null) ViewBag.Korisnik = kor.ime;
            //ViewBag.id_oper = new SelectList(db.Operateri, "id_oper", "Naziv", telefonija.id_oper);
            //ViewBag.id_zaposlenici = new SelectList(db.Zaposlenici, "id_zaposlenici", "ImePrezime", telefonija.id_zaposlenici);
            //ViewBag.id_tip = new SelectList(db.Tip_Telefona, "id_tip", "Naziv", telefonija.id_tip);
            return View(telefonija);
        }

        public ActionResult SumarnoNewPage(int id)
        {
            var telefonija = (from t in db.Telefonija where t.id_tel == id select t).FirstOrDefault();
            if (telefonija != null)
            {
                ViewBag.Korisnik = telefonija.Zaposlenici.ImePrezime;
                ViewBag.broj = telefonija.broj_tel;
                ViewBag.Limit = telefonija.Limit;
                ViewBag.id_tel = id;
                ViewBag.id_zap = telefonija.id_zaposlenici;
            }
            var god = new List<string> {"2012", "2013", "2014"};
            ViewBag.godina = new SelectList(god);

            var mj = new List<string> {"1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"};
            ViewBag.mjesec = new SelectList(mj); 


            //ViewBag.id_oper = new SelectList(db.Operateri, "id_oper", "Naziv", telefonija.id_oper);
            //ViewBag.id_zaposlenici = new SelectList(db.Zaposlenici, "id_zaposlenici", "ImePrezime", telefonija.id_zaposlenici);
            //ViewBag.id_tip = new SelectList(db.Tip_Telefona, "id_tip", "Naziv", telefonija.id_tip);
            return View();
        }

        public ActionResult DetaljnoPage(string id)
        {

            var telefonija = (from t in db.vEronetPotrosnja where t.idlnk == id select t).ToList();
            var zb = (from t in db.vEronetPotrosnja where t.idlnk == id select t.Iznos).Sum();
            if (zb != null) ViewBag.zbroj = Math.Round((double) zb,2).ToString("0.00");

            var kor  =
                (from tt in db.vEronetPotrosnja
                 where tt.idlnk == id
                 select tt).FirstOrDefault();

            if (kor != null) ViewBag.Korisnik = kor.MJESEC + " - " + kor.GODINA;

            //ViewBag.id_oper = new SelectList(db.Operateri, "id_oper", "Naziv", telefonija.id_oper);
            //ViewBag.id_zaposlenici = new SelectList(db.Zaposlenici, "id_zaposlenici", "ImePrezime", telefonija.id_zaposlenici);
            //ViewBag.id_tip = new SelectList(db.Tip_Telefona, "id_tip", "Naziv", telefonija.id_tip);
            return View(telefonija);
        }
        
        //
        // POST: /Phone/Create

        [HttpPost]
        public ActionResult Create(Telefonija telefonija)
        {
            if (ModelState.IsValid)
            {
                db.Telefonija.AddObject(telefonija);
                db.SaveChanges();
                return RedirectToAction("Index");  
            }

            var zap = (from z in db.Zaposlenici where z.datum_prestanka == null select z);
            ViewBag.id_zaposlenici = new SelectList(zap, "id_zaposlenici", "Ime", telefonija.id_zaposlenici);
            ViewBag.id_tip = new SelectList(db.Tip_Telefona, "id_tip", "Naziv", telefonija.id_tip);
            return View(telefonija);
        }

         [HttpPost]
        public ActionResult SumarnoNewPage(PotrosnjaSumarno potr, decimal limit, int id_tel, int id_zap ,string broj_tel)
        {
            //var telefonija = (from t in db.Telefonija where t.id_tel == id select t).FirstOrDefault();
             var kor = ViewBag.Limit;
             if(ModelState.IsValid)
             {

                 // provjera da li se plaća cijeli iznos
                 var lm = (from l in db.Telefonija where l.id_tel == id_tel select l.UkupnoLimit).FirstOrDefault();
                 if(potr.broj_tel.Contains("38765") || potr.broj_tel.Contains("38766"))
                     potr.iznos = Math.Round(potr.iznos.Value *   Convert.ToDecimal( 1.17),2);

                 potr.id_tel = id_tel;
                 potr.id_zaposlenici = id_zap;
                 potr.odob_limit = limit;

                 var kor_iz = potr.iznos - potr.limit;

                 if (kor_iz < 0)
                     kor_iz = 0;

                 if (potr.iznos <= limit)
                     potr.limit = potr.iznos;

                 potr.iznos_kor = kor_iz;
                 // ako banka plaća cijeli iznos
                 if(lm)
                 {
                     potr.iznos_kor = 0;
                     potr.limit = potr.iznos;
                 }
                 
                 potr.broj_tel = broj_tel;

                 db.AddToPotrosnjaSumarno(potr);
                 db.SaveChanges();

                 return RedirectToAction("SumarnoPage", new { id = id_tel });  
             }

             var telefonija = (from t in db.Telefonija where t.id_tel == id_tel select t).FirstOrDefault();
             if (telefonija != null)
             {
                 ViewBag.Korisnik = telefonija.Zaposlenici.ImePrezime;
                 ViewBag.broj = telefonija.broj_tel;
                 ViewBag.Limit = telefonija.Limit;
                 ViewBag.id_tel = id_tel;

Mobiteli/Controllers/RazduzenjaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Mobiteli.Models;

namespace Mobiteli.Controllers
{ 
    public class RazduzenjaController : TemplateController
    {
    
        //
        // GET: /Razduzenja/

        public ViewResult Index()
        {
            var razduzenje = db.Razduzenje.Include("Telefonija");
            return View(razduzenje.ToList());
        }

        //
        // GET: /Razduzenja/Details/5

  

        //
        // POST: /Razduzenja/Edit/5

        [HttpPost]
        public ActionResult Edit(Razduzenje razduzenje)
        {
            if (ModelState.IsValid)
            {
                db.Razduzenje.Attach(razduzenje);
                db.ObjectStateManager.ChangeObjectState(razduzenje, EntityState.Modified);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.id_tel = new SelectList(db.Telefonija, "id_tel", "broj_tel", razduzenje.id_tel);
            return View(razduzenje);
        }

        //
        // GET: /Razduzenja/Delete/5

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Mobiteli/Controllers/UredjajiController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Mobiteli.Models;
using PagedList;

namespace Mobiteli.Controllers
{ 
    public class UredjajiController : Controller
    {
        private EvidencijaEntities db = new EvidencijaEntities();

        //
        // GET: /Uredjaji/

        public ViewResult Index(string sortOrder, string currentFilter, string searchString, int? page, string rbSve)
        {
            //ViewBag.CurrentSort = sortOrder;
            //ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "Ime desc" : "";
            //ViewBag.BrojSortParm = sortOrder == "Broj" ? "Broj desc" : "Broj";

            if (Request.HttpMethod == "GET")
            {
                searchString = currentFilter;
            }
            else
            {
                page = 1;
            }
            ViewBag.CurrentFilter = searchString;

            ViewBag.RadioVal = 1;

            var students =(from d in  db.Uredjaji select d).OrderBy(s=>s.id_ur) .Include("Modeli_Uredjaja").Include("Operateri");

            if (!String.IsNullOrEmpty(searchString))
            {
                students = students.Where(s => s.Modeli_Uredjaja.Naziv.ToUpper().Contains(searchString.ToUpper())
                                       || s.IMEI.ToUpper().Contains(searchString.ToUpper())
                                        || s.Operateri.Naziv.ToUpper().Contains(searchString.ToUpper())
                                       );
            }
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(students.ToPagedList(pageNumber, pageSize)); 
            //var uredjaji = db.Uredjaji.Include("Modeli_Uredjaja").Include("Operateri");
            //return View(uredjaji.ToList());
        }

        //
        // GET: /Uredjaji/Details/5

        public ViewResult Details(int id)
        {
            Uredjaji uredjaji = db.Uredjaji.Single(u => u.id_ur == id);
            return View(uredjaji);
        }

        //
        // GET: /Uredjaji/Create

        public ActionResult Create()
        {
            ViewBag.id_model = new SelectList(db.Modeli_Uredjaja, "id_model", "Naziv");
            ViewBag.id_oper = new SelectList(db.Operateri, "id_oper", "Naziv");
            return View();
        } 

        //
        // POST: /Uredjaji/Create

        [HttpPost]
        public ActionResult Create(Uredjaji uredjaji)
        {
            if (ModelState.IsValid)
            {
                db.Uredjaji.AddObject(uredjaji);
                db.SaveChanges();
                return RedirectToAction("Index");  
            }

            ViewBag.id_model = new SelectList(db.Modeli_Uredjaja, "id_model", "Naziv", uredjaji.id_model);
            ViewBag.id_oper = new SelectList(db.Operateri, "id_oper", "Naziv", uredjaji.id_oper);
            return View(uredjaji);
        }
        
        //
        // GET: /Uredjaji/Edit/5
 
        public ActionResult Edit(int id)
        {
            Uredjaji uredjaji = db.Uredjaji.Single(u => u.id_ur == id);
            ViewBag.id_model = new SelectList(db.Modeli_Uredjaja, "id_model", "Naziv", uredjaji.id_model);
            ViewBag.id_oper = new SelectList(db.Operateri, "id_oper", "Naziv", uredjaji.id_oper);
            return View(uredjaji);
        }

        //
        // POST: /Uredjaji/Edit/5

        [HttpPost]
        public ActionResult Edit(Uredjaji uredjaji)
        {
            if (ModelState.IsValid)
            {
                db.Uredjaji.Attach(uredjaji);
                db.ObjectStateManager.ChangeObjectState(uredjaji, EntityState.Modified);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.id_model = new SelectList(db.Modeli_Uredjaja, "id_model", "Naziv", uredjaji.id_model);
            ViewBag.id_oper = new SelectList(db.Operateri, "id_oper", "Naziv", uredjaji.id_oper);
            return View(uredjaji);
        }

        //
        // GET: /Uredjaji/Delete/5
 
        public ActionResult Delete(int id)
        {
            Uredjaji uredjaji = db.Uredjaji.Single(u => u.id_ur == id);
            return View(uredjaji);
        }

        //
        // POST: /Uredjaji/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {            
            Uredjaji uredjaji = db.Uredjaji.Single(u => u.id_ur == id);
            db.Uredjaji.DeleteObject(uredjaji);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Mobiteli/Views/Shared/DateTime.cshtml
@model DateTime? 
@Html.TextBox("", (Model.HasValue ? Model.Value.ToShortDateString() : string.Empty), new { @class = "date-pick", style = "width:150px" }) 

<script src="../../Scripts/jquery-ui-1.8.11.js" type="text/javascript"></script>

<link href="../../Content/themes/base/jquery.ui.all.css" rel="stylesheet" type="text/css" />
<script type="text/javascript">
    $(function () {
        $('.date-pick');
        $('.date-pick').datepicker({
            dateFormat: 'dd/mm/yy',
            showStatus: true,
            showWeeks: false,
            highlightWeek: true,
            numberOfMonths: 1,
            showAnim: "scale",
            showOptions: {
                origin: ["top", "left"]
            } 
        });
    });   
</script> 

Mobiteli/Views/Shared/DetaljnoPage.cshtml
@using Mobiteli.Models
@model IEnumerable<Mobiteli.Models.vEronetPotrosnja>

@{
    ViewBag.Title = "Pregled potrošnje za :" + @ViewBag.Korisnik;
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<table id="hor-minimalist-b">
    <tr>
        <th>SIFRA</th>
        <th>OPIS STAVKE</th>
        <th>Iznos KM</th>
    </tr>

    @foreach (vEronetPotrosnja item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.SIFRA)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OPIS_STAVKE)
            </td>
            <td style="text-align: right">
                @{
                    decimal dd = Math.Round((decimal) item.Iznos, 2);
                    @Html.DisplayFor(modelItem => dd)
                }
            </td>
        </tr>
    }
    <tr>
        <th></th>
        <th>Ukupno:</th>
        <th style="text-align: right">@ViewBag.zbroj</th>
    </tr>
</table>

@section link
{
    @Html.ActionLink("Natrag", "Index")
}

Mobiteli/Views/Shared/PageListView.cshtml
<hr>
<div align="center"> 
 @if (Model.HasPreviousPage)
{
    @Html.ActionLink("<<", "Index", new { page = 1, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter })
    @Html.Raw(" ")
    @Html.ActionLink("< Prev", "Index", new { page = Model.PageNumber - 1, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter })
}
else
{
    @:<< 
    @Html.Raw(" ")
    @:< Prev 
} 
-  
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) 
of @Model.PageCount   -  
@if (Model.HasNextPage)
{
    @Html.ActionLink("Next >", "Index", new { page = Model.PageNumber + 1, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter })
    @Html.Raw(" ")
    @Html.ActionLink(">>", "Index", new { page = Model.PageCount, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter })
}
else
{
    @:Next > 
    @Html.Raw(" ")
    @:>> 
} 
</div>

Mobiteli/Views/Shared/RazduzenjePotvrda.cshtml
@using DevExpress.Web.Mvc.UI
@model Mobiteli.Models.Razduzenje

@{
    ViewBag.Title = "Potvrda Razduzenje";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <table>
        @Html.HiddenFor(model => model.id_raz)
        <tr>
            <td class="col1">Zaposlenik</td>
            <td class="col2">
                @Html.DisplayFor(model => model.Telefonija.Zaposlenici.ImePrezime)
            </td>
        </tr>
        <tr>
            <td class="col1"> Broj telefona</td>
            <td class="col2">
                @Html.DisplayFor(model => model.Telefonija.broj_tel)
            </td>
        </tr>
        <tr>
            <td class="col1">Datum razduženja</td>
            <td class="col2">
                @Html.DisplayFor(model => model.datum_razduzenja)
            </td>
        </tr>
        <tr>
            <td class="col1">Opis</td>
            <td class="col2">
                @Html.DisplayFor(model => model.opis)
            </td>
        </tr>

    </table>
    <table>
                        <tr>
                            <td>
                                @Html.DevExpress().Button(
                                        settings =>
                                            {
                                                settings.Name = "btnUpdate";
                                                settings.ControlStyle.CssClass = "button";
                                                settings.Text = "Potvrda";
                                                settings.UseSubmitBehavior = true;
                                            }
                                        )
                                        .Render();
                            </td>
                            <td>
                                @Html.DevExpress().Button(
                                        settings =>
                                            {
                                                settings.Name = "btnCancel";
                                                settings.ControlStyle.CssClass = "button";
                                                settings.Text = "Odbiti";
                                                settings.UseSubmitBehavior = true;
                                            }
                                        )
                                        .Render();

                            </td>
                        </tr>
                    </table>  
}

@section link
{
    @Html.ActionLink("Natrag", "Index")
}

Mobiteli/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
    <head style="width: 100%">
        <title>@ViewBag.Title</title>
        <link href=@Url.Content("~/Content/Site.css") rel="stylesheet" type="text/css" />
        <script src="@Url.Content("~/Scripts/jquery-1.5.1.min.js")" type="text/javascript"> </script>

    </head>

    <body >
        
        <div class="page">
           
            <table style="background-color: #8496A6; width: 100%;">
                <tr style="border-style: none">
                    <td >
                        <div id="header">
                            <div id="logo">
                                <h1>&nbsp;@ViewBag.Title</h1>
                                korisnik: <strong>@User.Identity.Name</strong>!
                            </div> 
                        </div>
                    </td>
                    <td style="text-align: right">
                        <div id="menucontainer">
                            <ul id="menu">
                                @if (User.Identity.Name == "HYPO\\zeljkoc" || User.Identity.Name == "HYPO\\slavenf"
                                     || User.Identity.Name == "HYPO\\ivanb")
                                {
                                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                                    <li>@Html.ActionLink("Fiksna Tel", "Index", "Fiksna")</li>
                                    <li>@Html.ActionLink("Zaduženja brojeva", "Index", "Phone")</li>
                                    <li>@Html.ActionLink("Zaduženja Uređaja", "Index", "DeviceUse")</li>
                                    <li>@Html.ActionLink("Uređaji", "Index", "Uredjaji")</li>
                                    <li>@Html.ActionLink("Razduženje", "Index", "Razduzenja")</li>                                    
                                    <li>@Html.ActionLink("Servis", "Index", "Servis")</li>
                                    <li>@Html.ActionLink("OD", "Index", "OD")</li>
                                    <li>@Html.ActionLink("Zaposlenici", "Index", "Zaposlenici")</li>
                                }
                            </ul>
                        </div>
                    </td>
                </tr>
            </table>
            <table style="width: 100%">
                <tr>
                    <td style="width: 100px; vertical-align: top;">
                        <div id = "linksbar" class="box">
                            @RenderSection("link",false)   
                        </div>
                    </td>
                    <td>
                    <div id="content" >
                            @RenderBody()
                    </div> 
                    </td>
                </tr>
            </table>          
              
         <div id="footer">
                    <hr/>
                    HYPO Alpe-Adria Bank dd Mostar   
                </div>
        </div>
    </body>
</html>